name: Use Action

on:
  push:
    branches:
      - 'master'

jobs:
  use-action:
    name: Use Action

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: actions/checkout@v4

      # Minimal publish
      - uses: mscno/setup-goose@master

      - run: goose -version

      - name: Install old release
        uses: mscno/setup-goose@master
        with:
          version: v3.15.0

      - name: Check installed version
        run: goose -version | grep 3.15.0

      - name: Install from tip
        uses: mscno/setup-goose@master
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          goose -version
